<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "achievements".
 *
 * @property int $id
 * @property int $main_id
 * @property int $main_type
 * @property int $achievement_id
 *
 * @property AchievementsList $achievement
 */
class Achievements extends \yii\db\ActiveRecord
{
    const MAIN_TYPE_USER = 0;
    const MAIN_TYPE_SERVER = 1;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'achievements';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['main_id', 'main_type', 'achievement_id'], 'required'],
            [['main_id', 'main_type', 'achievement_id'], 'integer'],
            [['achievement_id'], 'exist', 'skipOnError' => true, 'targetClass' => AchievementsList::className(), 'targetAttribute' => ['achievement_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'main_id' => Yii::t('app', 'Main ID'),
            'main_type' => Yii::t('app', 'Main Type'),
            'achievement_id' => Yii::t('app', 'Achievement ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAchievement()
    {
        return $this->hasOne(AchievementsList::className(), ['id' => 'achievement_id']);
    }

    public function beforeSave($insert)
    {
        $activity = new Activity();
        $activity->main_id = $this->main_id;
        $activity->main_type = $this->main_type;

        if ($this->main_type == self::MAIN_TYPE_SERVER) {
            $server = Servers::findOne(['id' => $this->main_id]);

            $activity->type = Activity::TYPE_NEW_SERVER_ACHIEVEMENT;
            $activity->data = json_encode([
                'server_title' => $server->title,
                'achievement_title' => $this->achievement->description,
            ]);
        } else {
            $user = User::findOne(['id' => $this->main_id]);

            $activity->type = Activity::TYPE_NEW_USER_ACHIEVEMENTS;
            $activity->data = json_encode([
                'username' => $user->username,
                'achievement_title' => $this->achievement->description,
            ]);
        }

        $activity->save();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
